apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-mgmt-role
  namespace: velero
rules:
- apiGroups: ["velero.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]