version: '3.0'
services:
  velero-api-stack:
    container_name: velero-api
    image: velero-api:1.3
    #restart: always
    network_mode: host
    command: ["python3", "-u", "main.py"]
    working_dir: /app
    volumes:
      - velero_api_config:/root/.kube
      - /etc/localtime:/etc/localtime:ro
    environment:
    - CONTAINER_MODE=True
    - VELERO_CLI_PATH=./velero-client
    - VELERO_CLI_PATH_CUSTOM=./velero-client-binary
    - VELERO_CLI_VERSION=v1.12.2
    - VELERO_CLI_DEST_PATH=/bin
    - API_ENDPOINT_PORT=8001
    - VELERO_NAMESPACE=velero
    - ORIGINS=["http://localhost:3000", "http://127.0.0.1:3000"]
    - SECURITY_TOKEN_KEY=<your-token-key >
    - SECURITY_REFRESH_TOKEN_KEY=<your-token-key >
    - SECURITY_PATH_DATABASE=./data
    - DEFAULT_ADMIN_USERNAME=admin
    - DEFAULT_ADMIN_PASSWORD=admin
    ports:
      - "8001:8001"
volumes:
  velero_api_config:
    external: true
