apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name:  velero-api-ingress
# annotations:
#    kubernetes.io/ingress.class: nginx
# labels:
#   app.kubernetes.io/instance: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: velero.your-tests-domain
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: velero-api-lb
            port:
              number: 80
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: velero-api-lb
            port:
              number: 80
