name: 'Mark stale issues and pull requests'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue has been automatically marked as stale due to inactivity for 14 days. 
            It will be closed in 7 days if no further activity occurs.
          close-issue-message: >
            Closing this issue due to prolonged inactivity. Feel free to reopen if needed.
          days-before-stale: 12
          days-before-close: 7
          stale-issue-label: 'stale'
          exempt-issue-labels: 'enhancement,bug'
